version: "3"

services:
    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
        volumes:
            - ./services/redis:/data
        container_name: "redis"
        restart: always
    beanstalkd:
        image: schickling/beanstalkd
        ports:
            - "11300:11300"
        volumes:
            - ./services/beanstalkd/beanstalkd:/etc/conf.d/beanstalkd 
            - ./services/beanstalkd:/var/lib/beanstalkd
        container_name: "beanstalkd"
        restart: always
    memcached:
        image: memcached:alpine
        ports:
            - "11211:11211"
        volumes:
            - ./services/memcached:/usr/local/include/memcached
        container_name: "memcached"
        restart: always
    mongo:
        image: mongo
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: admin
        volumes:
           # - ./services/mongo/conf/mongod.conf:/etc/mongod.conf
            - ./services/mongo:/data/db
        #command: --serviceExecutor adaptive --config /etc/mongo/mongod.conf
        container_name: "mongo"
        restart: always
    mongo-express:
        image: mongo-express
        ports:
            - "8082:8081"
        restart: always
        environment:
            ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
            ME_CONFIG_MONGODB_SERVER: mongo
            ME_CONFIG_BASICAUTH_USERNAME: admin
            ME_CONFIG_BASICAUTH_PASSWORD: admin
            ME_CONFIG_MONGODB_ADMINUSERNAME: admin
            ME_CONFIG_MONGODB_ADMINPASSWORD: admin
        volumes:
            - ./services/mongo/mongo-express/config.js:/node_modules/mongo-express/config.js
        container_name: "mongo-express"
        links:
            - mongo
networks:
  default:
    driver: bridge