---
version: '3.7'
services:
  mongod:
    container_name: mongod
    image: docker.nodevops.cn/web/mongo:3.7
    ports:
      - 27017:27017
    #environment:
      #MONGO_INITDB_ROOT_USERNAME: admin
      #MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./mongod/mongod.conf:/etc/mongod.conf
      - /data/docker/mongo/data:/data/db
    #command: --serviceExecutor adaptive --config /etc/mongo/mongod.conf
    restart: always
