---
version: '3.7'
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet:   172.1.0.1/24
services:
    gitlab:
        container_name: gitlab
        image: docker.nodevops.cn/gitlab/gitlab-ce:12.10.14-ce.0
        volumes:
            - ./gitlab:/etc/gitlab
            - /data/docker/gitlab/log:/var/log/gitlab
            - /data/docker/gitlab/opt:/var/opt/gitlab
        ports:
            - '22:22'
            - 80:80
            - 443:443
    gitlab8.8:
        container_name: gitlab8.8
        image: docker.nodevops.cn/web/gitlab:8.8.7-ce.1-zh
        volumes: 
            - ./gitlab:/etc/gitlab
            - /data/docker/gitlab/log:/var/log/gitlab
            - /data/docker/gitlab/opt:/var/opt/gitlab
        ports:
            - '22:22'
            - 80:80
            - 443:443
    gitlab8.17:
        container_name: gitlab8.17
        image: docker.nodevops.cn/gitlab/gitlab-ce:8.17.8-ce.0
        volumes: 
            - ./gitlab:/etc/gitlab
            - /data/docker/gitlab/log:/var/log/gitlab
            - /data/docker/gitlab/opt:/var/opt/gitlab
        ports:
            - '22:22'
            - 80:80
            - 443:443
    gitlab9.0:
        container_name: gitlab9.0
        image: docker.nodevops.cn/gitlab/gitlab-ce:9.0.0-ce.0
        volumes: 
            - ./gitlab:/etc/gitlab
            - /data/docker/gitlab/log:/var/log/gitlab
            - /data/docker/gitlab/opt:/var/opt/gitlab
        ports:
            - '22:22'
            - 80:80
            - 443:443
    gitlab9.5:
        container_name: gitlab9.5
        image: docker.nodevops.cn/gitlab/gitlab-ce:9.5.9-ce.0
        volumes: 
            - ./gitlab:/etc/gitlab
            - /data/docker/gitlab/log:/var/log/gitlab
            - /data/docker/gitlab/opt:/var/opt/gitlab
        ports:
            - '22:22'
            - 80:80
            - 443:443
    gitlab10.0:
        container_name: gitlab10.0
        image: docker.nodevops.cn/gitlab/gitlab-ce:10.0.0-ce.0
        volumes: 
            - ./gitlab:/etc/gitlab
            - /data/docker/gitlab/log:/var/log/gitlab
            - /data/docker/gitlab/opt:/var/opt/gitlab
        ports:
            - '22:22'
            - 80:80
            - 443:443
    gitlab10.8:
        container_name: gitlab10.8
        image: docker.nodevops.cn/gitlab/gitlab-ce:10.8.7-ce.0
        volumes: 
            - ./gitlab:/etc/gitlab
            - /data/docker/gitlab/log:/var/log/gitlab
            - /data/docker/gitlab/opt:/var/opt/gitlab
        ports:
            - '22:22'
            - 80:80
            - 443:443
    gitlab11.0:
        container_name: gitlab11.0
        image: docker.nodevops.cn/gitlab/gitlab-ce:11.0.0-ce.0
        volumes: 
            - ./gitlab:/etc/gitlab
            - /data/docker/gitlab/log:/var/log/gitlab
            - /data/docker/gitlab/opt:/var/opt/gitlab
        ports:
            - '22:22'
            - 80:80
            - 443:443
    gitlab11.11:
        container_name: gitlab11.11
        image: docker.nodevops.cn/gitlab/gitlab-ce:11.11.8-ce.0
        volumes: 
            - ./gitlab:/etc/gitlab
            - /data/docker/gitlab/log:/var/log/gitlab
            - /data/docker/gitlab/opt:/var/opt/gitlab
        ports:
            - '22:22'
            - 80:80
            - 443:443
    gitlab12.0:
        container_name: gitlab12.0
        image: docker.nodevops.cn/gitlab/gitlab-ce:12.0.0-ce.0
        volumes: 
            - ./gitlab:/etc/gitlab
            - /data/docker/gitlab/log:/var/log/gitlab
            - /data/docker/gitlab/opt:/var/opt/gitlab
        ports:
            - '22:22'
            - 80:80
            - 443:443
    gitlab12.3:
        container_name: gitlab12.3
        image: docker.nodevops.cn/gitlab/gitlab-ce:12.3.9-ce.0
        volumes: 
            - ./gitlab:/etc/gitlab
            - /data/docker/gitlab/log:/var/log/gitlab
            - /data/docker/gitlab/opt:/var/opt/gitlab
        ports:
            - '22:22'
            - 80:80
            - 443:443
    gitlab12.10:
        container_name: gitlab12.10
        image: docker.nodevops.cn/gitlab/gitlab-ce:12.10.14-ce.0
        volumes:
            - ./gitlab:/etc/gitlab
            - /data/docker/gitlab/log:/var/log/gitlab
            - /data/docker/gitlab/opt:/var/opt/gitlab
        ports:
            - '22:22'
            - 80:80
            - 443:443
    gitlab12:
        container_name: gitlab12
        image: docker.nodevops.cn/gitlab/gitlab-ce:12.10.14-ce.0
        volumes:
            - ./gitlab:/etc/gitlab
            - /data/docker/gitlab/log:/var/log/gitlab
            - /data/docker/gitlab/opt:/var/opt/gitlab
        ports:
            - '22:22'
            - 80:80
            - 443:443
