help:
    make stop
    make start
    make restart
init:
    systemctl enable haproxy
    systemctl status haproxy
stop:
    systemctl stop haproxy
start:
    systemctl start haproxy
restart:
    systemctl stop haproxy
    systemctl start haproxy