version: "3"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
#      - ./my/custom/mongod.conf:/etc/mongod.conf
      - ./data:/data/db
#    command: --serviceExecutor adaptive --config /etc/mongo/mongod.conf
    restart: always
  mongo-express:
    image: mongo-express
    ports:
      - 8082:8081
    restart: always
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
    volumes:
      - ./config.js:/node_modules/mongo-express/config.js
    links:
       - mongo




# https://www.cnblogs.com/cwp-bg/p/10403327.html
